[package]
name = "oc_spray"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
soloud = { version = "1", default-features = false, features = ["alsa"] }
rand = "0.8.4"


